apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: oaas-observability
  labels:
    app: jaeger
spec:
  selector:
    app: jaeger
  ports:
    - name: ui
      port: 16686
      targetPort: 16686
    - name: otlp-grpc
      port: 4317
      targetPort: 4317
  type: ClusterIP
