apiVersion: v1
kind: Service
metadata:
  name: tempo
  namespace: oaas-observability
  labels:
    app: tempo
spec:
  selector:
    app: tempo
  ports:
    - name: http
      port: 3200
      targetPort: 3200
    - name: grpc
      port: 4317
      targetPort: 4317
  type: ClusterIP
