apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: oaas-observability
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus:v2.49.1
          imagePullPolicy: IfNotPresent
          args:
            - '--config.file=/etc/prometheus/prometheus.yaml'
          ports:
            - containerPort: 9090
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9090
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9090
            initialDelaySeconds: 30
            periodSeconds: 20
          volumeMounts:
            - name: prometheus-config
              mountPath: /etc/prometheus/prometheus.yaml
              subPath: prometheus.yaml
            - name: prometheus-rules
              mountPath: /etc/prometheus/rules/test-alerts.yaml
              subPath: test-alerts.yaml
            - name: prometheus-storage
              mountPath: /prometheus
      volumes:
        - name: prometheus-config
          configMap:
            name: prometheus-config
            items:
              - key: prometheus.yaml
                path: prometheus.yaml
        - name: prometheus-rules
          configMap:
            name: prometheus-config
            items:
              - key: test-alerts.yaml
                path: test-alerts.yaml
        - name: prometheus-storage
          emptyDir: {}
