[tool.poetry]
name = "tic tac toe"
version = "0.1.0"
description = "Tic Tac Toe Backend"
authors = ["Dilip Sharma"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~=3.13"
opentelemetry-distro = "^0.51b0"
opentelemetry-instrumentation-fastapi = "^0.51b0"
opentelemetry-api = "^1.30.0"
opentelemetry-exporter-otlp = "^1.30.0"
pydantic-settings = "^2.7.1"
opentelemetry-sdk = "^1.30.0"


[tool.poetry.group.core.dependencies]
fastapi = "^0.115.8"
uvicorn = "^0.34.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
