apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-data
  namespace: oaas-observability
  labels:
    app: loki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: loki-wal
  namespace: oaas-observability
  labels:
    app: loki
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
