apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-data
  namespace: oaas-observability
  labels:
    app: opensearch-core
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
