apiVersion: v1
kind: Service
metadata:
  name: opensearch-core
  namespace: oaas-observability
  labels:
    app: opensearch-core
spec:
  selector:
    app: opensearch-core
  ports:
    - name: http
      port: 9200
      targetPort: 9200
  type: ClusterIP
