apiVersion: 1

# Provision Tempo as a data source for traces in Grafana
# This file will be loaded automatically by Grafana on startup

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      httpMethod: GET
      nodeGraph:
        enabled: true
      serviceMap:
        enabled: true