{
 "title": "application_overview",
 "time": { "from": "now-2d", "to": "now" },
 "panels": [
  {
   "title": "HTTP Request Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_request_duration_seconds_bucket[$__interval])) by (le, method, path))",
     "legendFormat": "{{method}} {{path}} (p50"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(http_request_duration_seconds_bucket[$__interval])) by (le, method, path))",
     "legendFormat": "{{method}} {{path}} (p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[$__interval])) by (le, method, path))",
     "legendFormat": "{{method}} {{path}} (p95)"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket[$__interval])) by (le, method, path))",
     "legendFormat": "{{method}} {{path}} (p99)"
    }
   ]
  },
  {
   "title": "HTTP Error Rate (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "increase(http_server_requests_total{status_code=~\"5..\"}[$__interval])",
     "legendFormat": "{{method}} {{path}}"
    }
   ]
  },
  {
   "title": "HTTP Requests: Count & Duration",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (method, path, status_code) (http_server_requests_total)",
     "legendFormat": "{{method}} {{path}} ({{status_code}})"
    },
    {
     "expr": "sum by (method, path, status_code) (http_request_duration_seconds_sum)\n/\nsum by (method, path, status_code) (http_request_duration_seconds_count)",
     "legendFormat": "{{method}} {{path}} ({{status_code}})"
    }
   ]
  },
  {
   "title": "HTTP Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "sum by (method, path) (rate(http_server_requests_total[1m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}