apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: tic-tac-toe
data:
  OTEL_EXPORTER_LOGS_ENDPOINT: "http://otel-collector:4318/v1/logs"
  OTEL_EXPORTER_TRACES_ENDPOINT: "http://otel-collector:4318/v1/traces"
  OTEL_EXPORTER_METRICS_ENDPOINT: "http://otel-collector:4318/v1/metrics"
  OTEL_SERVICE_NAME: "tic-tac-toe-backend"
  RATE_LIMITED_LOG_INTERVAL_SECONDS: "2"
